services:
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    ports:
      - '8080:8080'
    volumes:
      - "$PWD/dags:/opt/airflow/dags"
      - "$PWD/scripts:/scripts"
    entrypoint: 'sh /scripts/init_airflow.sh'
    restart: 'always'